title: '[Announcement]  '
labels: ['Announcement']
body:
  - type: markdown
    attributes:
      value: |
        Announcement
  - type: textarea
    id: improvements and changes
    attributes:
      label: Top 3 improvements and changes
      description: 'What are the top 3 improvements we could make to this project?'
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Additional
        And some more additionals
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - New Features
        - Pull request review time
        - testing improvements
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: new release version
      options:
        - label: yes, it has deployed with new version
        - label: no, it's not version change
